import Footer from '../../components/Footer'
import Navbar from '../../components/Navbar'
import './globals.css'
import { Quicksand } from 'next/font/google'

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const oswald = Quicksand({
  weight: '500',
  subsets: ['latin'],
})
export const metadata = {
  title: 'Poters Temple Church',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${oswald.className}`}>
      <Navbar />
        {children}
      <Footer />
        
        </body>
    </html>
  )
}
